alter table CIFRA_JOURNAL add constraint FK_CIFRA_JOURNAL_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references CIFRA_EMPLOYEE(ID);
alter table CIFRA_JOURNAL add constraint FK_CIFRA_JOURNAL_ON_WAREHOUSE foreign key (WAREHOUSE_ID) references CIFRA_WAREHOUSE(ID);
alter table CIFRA_JOURNAL add constraint FK_CIFRA_JOURNAL_ON_HOLDER foreign key (HOLDER_ID) references CIFRA_EMPLOYEE(ID);
create index IDX_CIFRA_JOURNAL_ON_RESPONSIBLE on CIFRA_JOURNAL (RESPONSIBLE_ID);
create index IDX_CIFRA_JOURNAL_ON_WAREHOUSE on CIFRA_JOURNAL (WAREHOUSE_ID);
create index IDX_CIFRA_JOURNAL_ON_HOLDER on CIFRA_JOURNAL (HOLDER_ID);
